### ISSUE TITLE
Better name for `calculate_residualnorm`

### ISSUE THREAD

**Issue by KnutAM** [KnutAM/FESolvers.jl#2]
The name: `calculate_residualnorm` is misleading, as the function should return a number to be compared with the nonlinear solver's tolerance which could also be e.g. the norm of the correction or anything else that the user defines (e.g. combination of multiple values). 

Suggestions (to be updated)
1. `calculate_iteration_error` 
1. `calculate_error`
1. `calculate_tolerance_comparison_value`

**Comment by koehlerson** [comment]
`calculate_convergence_criterion` ?

`error` is probably too ambiguous since it's heavily used w.r.t. the discretization error and number 3 is too long, something with at max 3 words would be nice

**Comment by KnutAM** [comment]
I agree, "error" is not so nice here.  
I think your suggestion is the best, so let's go with that!
